#!/bin/sh
# Xcode Cloud runs this after cloning, before building (it must sit next to the project).
# The Xcode project is generated by xcodegen and gitignored, so generate it here, as the
# GitHub CI workflow does.
set -eu

cd "$CI_PRIMARY_REPOSITORY_PATH/app"

# Optional: the signing team and iCloud entitlements (see Config/Signing.xcconfig.example).
# Set DEVELOPMENT_TEAM as a secret environment variable in the Xcode Cloud workflow so the
# team ID stays out of the public repo. Without it the app builds without iCloud.
if [ -n "${DEVELOPMENT_TEAM:-}" ]; then
  sed "s/^DEVELOPMENT_TEAM = .*/DEVELOPMENT_TEAM = $DEVELOPMENT_TEAM/" \
    Config/Signing.xcconfig.example > Config/Signing.xcconfig
fi

brew install xcodegen
xcodegen generate

# Xcode Cloud disables automatic package resolution and needs a Package.resolved, which
# lives inside the gitignored project, so restore the committed copy. When project.yml's
# packages change, copy the regenerated file back here; GitHub CI fails until you do.
resolved=PocketChef.xcodeproj/project.xcworkspace/xcshareddata/swiftpm
mkdir -p "$resolved"
cp ci_scripts/Package.resolved "$resolved/Package.resolved"
xcodebuild -resolvePackageDependencies -project PocketChef.xcodeproj -scheme PocketChef-iOS
