#!/bin/sh
# Xcode Cloud runs this after cloning, before building (it must sit next to the project).
# The Xcode project is generated by xcodegen and gitignored, so generate it here, as the
# GitHub CI workflow does.
set -eu

cd "$CI_PRIMARY_REPOSITORY_PATH/app"

# A release build starts from a tag (app/docs/release.md), which must name the version in
# project.yml, or App Store Connect would get a build under a different version than the tag.
if [ -n "${CI_TAG:-}" ]; then
  # The value may be quoted or not.
  version=$(sed -n 's/^ *MARKETING_VERSION: *"\{0,1\}\([^" ]*\)"\{0,1\} *$/\1/p' project.yml)
  if [ -z "$version" ]; then
    echo "error: no MARKETING_VERSION found in project.yml to check tag $CI_TAG against" >&2
    exit 1
  fi
  if [ "$CI_TAG" != "v$version" ]; then
    echo "error: tag $CI_TAG doesn't match MARKETING_VERSION $version in project.yml (expected v$version)" >&2
    exit 1
  fi
fi

# Optional: the signing team and iCloud entitlements (see Config/Signing.xcconfig.example).
# Set DEVELOPMENT_TEAM as a secret environment variable in the Xcode Cloud workflow so the
# team ID stays out of the public repo. Without it the app builds without iCloud.
if [ -n "${DEVELOPMENT_TEAM:-}" ]; then
  sed "s/^DEVELOPMENT_TEAM = .*/DEVELOPMENT_TEAM = $DEVELOPMENT_TEAM/" \
    Config/Signing.xcconfig.example > Config/Signing.xcconfig
fi

# Optional: the density API's host and read key (see Config/DensityAPI.xcconfig.example), from
# secret environment variables in the workflow. Without them the app never fetches densities.
if [ -n "${DENSITY_API_HOST:-}" ] && [ -n "${DENSITY_API_READ_KEY:-}" ]; then
  printf 'DENSITY_API_HOST = %s\nDENSITY_API_READ_KEY = %s\n' "$DENSITY_API_HOST" "$DENSITY_API_READ_KEY" \
    > Config/DensityAPI.xcconfig
fi

brew install xcodegen
xcodegen generate

# Xcode Cloud disables automatic package resolution and needs a Package.resolved, which
# lives inside the gitignored project, so restore the committed copy. When project.yml's
# packages change, copy the regenerated file back here; GitHub CI fails until you do.
resolved=PocketChef.xcodeproj/project.xcworkspace/xcshareddata/swiftpm
mkdir -p "$resolved"
cp ci_scripts/Package.resolved "$resolved/Package.resolved"
xcodebuild -resolvePackageDependencies -project PocketChef.xcodeproj -scheme PocketChef-iOS
