sonar.projectKey=neonpixel-software_pocket-chef
sonar.organization=neonpixel-software

sonar.sources=Sources
sonar.tests=Tests
sonar.sourceEncoding=UTF-8

sonar.cfamily.build-wrapper-output=bw-output
