// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PocketChef.DensityApi.Infrastructure;

#nullable disable

namespace PocketChef.DensityApi.Infrastructure.Migrations
{
    [DbContext(typeof(DensityApiDbContext))]
    partial class DensityApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PocketChef.DensityApi.Domain.DensityEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("GramsPerCup")
                        .HasColumnType("double precision");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.HasIndex("IngredientName")
                        .IsUnique()
                        .HasDatabaseName("IX_density_entries_IngredientName");

                    b.ToTable("density_entries", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
